### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by drewyoungren** [ccnmtl/mathplayground#309]
If possible, could one of you add a `.prettierrc` or `.editorconfig` with the CTL house style? I realize (finally) my prettier settings at home are making commits a mess.

**Comment by drewyoungren** [comment]
For instance I put up a quick fix of the missing level-curves button in `Function.svelte` in 73e7db81158 but I see it is hard to find the meat.

**Comment by nikolas** [comment]
Hmmm, good point. We always follow [eslint](https://eslint.org/)'s latest recommendations in our JS code, but as far as styling we don't have a hard and fast tool set up to enforce and exact code style.

In this realm, [black](https://github.com/psf/black) for Python, or Go's built-in `gofmt` tool provide code formatting in an automated way.

I would, for the most part, follow Google's JS style guide: https://google.github.io/styleguide/jsguide.html

With a few caveats we generally abide by:
* Use 4 spaces for indentation
* Use single-quotes instead of double-quotes unless otherwise necessary
* Max line length of 80 characters

Regarding the discrepancies in indentations within `if` clauses, my code style is influenced by whatever Emacs formats it to by default. E.g., whether to indent in a case like this or not is not a big deal either way - though I personally would keep the indent:

![Screenshot_2023-02-08_12-18-34](https://user-images.githubusercontent.com/59292/217604157-4001f58d-9ee7-45ee-ab30-6f14096d0674.png)


I have heard of [editorconfig](https://editorconfig.org/) before - we can look into putting in a config file for this or the prettier tool, if that's helpful.

**Comment by drewyoungren** [comment]
I think we're on the same page here.
